# Generated by Django 4.2.6 on 2023-10-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Walks',
            new_name='Walk',
        ),
    ]
