# Generated by Django 4.2.6 on 2023-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_walks_walk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='walk',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='walk',
            name='date',
            field=models.DateField(verbose_name='Walk Date'),
        ),
    ]
