# Generated by Django 4.2.6 on 2023-11-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bowl_alter_walk_options_alter_walk_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='pawrent',
        ),
    ]
