# Generated by Django 4.2.6 on 2023-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_dog_pawrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='bowls',
            field=models.ManyToManyField(to='main_app.bowl'),
        ),
    ]
